name: Fetch age

on:
  workflow_dispatch:
  #schedule:
    # runs at 00:01 UTC
    #- cron: "01 00, * * *"

jobs:
  refresh-feed:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch age
        id: fetch_age
        uses: JamesIves/fetch-api-data-action@v2
        with:
          endpoint: https://dev.davidfrings.dev/api/v1/age
          configuration: '{ "method": "GET" }'
          retry: true
          format: txt

      - name: Update README.md
        run: |
          sed -i "/<!--START_SECTION:age-->/,/<\!--END_SECTION:age-->/c\<!--START_SECTION:age-->$(cat $GITHUB_WORKSPACE/fetch-api-data-action/data.txt)<!--END_SECTION:age-->" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README.md with current age"
          git push
