name: Waka Readme (DE)

on:
  workflow_dispatch:
  schedule:
    # runs at 00:02 and 12:02 UTC
    - cron: "02 00,12 * * *"

jobs:
  update-readme:
    name: Update Readme with DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with: 
          #https://github.com/anmol098/waka-readme-stats#flags-available
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          LOCALE: "de"
          TARGET_PATH: "README.de.md"
          SECTION_NAME: "waka"
          COMMIT_BY_ME: "False"
          COMMIT_MESSAGE: "Updated with Dev Metrics"
          COMMIT_USERNAME: "GitHub Action Bot"
          COMMIT_EMAIL: "41898282+github-actions[bot]@users.noreply.github.com"
          SHOW_UPDATED_DATE: "True"
          UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
          SHOW_LINES_OF_CODE: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROFILE_VIEWS: "False"
          SHOW_COMMIT: "False"
          SHOW_DAYS_OF_WEEK: "True"
          SHOW_LANGUAGE: "True"
          SHOW_OS: "False"
          SHOW_PROJECTS: "True"
          SHOW_TIMEZONE: "False"
          SHOW_EDITORS: "True"
          SHOW_LANGUAGE_PER_REPO: "True"
          SHOW_SHORT_INFO: "True"
          SHOW_LOC_CHART: "False"
          COMMIT_SINGLE: "True"
          IGNORED_REPOS: "server, Velocity"
          SYMBOL_VERSION: "2"
          DEBUG_LOGGING: "True"
      #- uses: DavidFrings/waka-readme@master
      #  with:
      #    GH_TOKEN: ${{ secrets.GH_TOKEN }}
      #    WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
      #    ### meta
      #    API_BASE_URL: https://wakatime.com/api
      #    REPOSITORY: DavidFrings/DavidFrings
      #    ### content
      #    SHOW_TITLE: true # optional
      #    SECTION_NAME: waka # optional
      #    BLOCKS: ⣿⣀ # optional
      #    CODE_LANG: rust # optional
      #    TIME_RANGE: all_time # optional
      #    LANG_COUNT: 10 # optional
      #    SHOW_TIME: true # optional
      #    SHOW_TOTAL: true # optional
      #    SHOW_MASKED_TIME: false # optional
      #    STOP_AT_OTHER: true # optional
      #    IGNORED_LANGUAGES: NONE # optional
      #    ### commit
      #    COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
      #    TARGET_BRANCH: master # optional
      #    TARGET_PATH: README.md # optional
      #    COMMITTER_NAME: GitHub Action Bot
      #    COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
      #    #AUTHOR_NAME: DavidFrings
      #    #AUTHOR_EMAIL: david.frings.development@gmail.com
          
          # you can populate email-id with secrets instead
          ### content
          #SHOW_TITLE: true # optional
          #SECTION_NAME: waka # optional
          #BLOCKS: => # optional
          #CODE_LANG: rust # optional
          #TIME_RANGE: all_time # optional
          #LANG_COUNT: 10 # optional
          #SHOW_TIME: true # optional
          #SHOW_TOTAL: true # optional
          #SHOW_MASKED_TIME: false # optional
          #STOP_AT_OTHER: true # optional
          ### commit
          #COMMIT_MESSAGE: Updated waka-readme graph with new metrics # optional
          #TARGET_BRANCH: master # optional
          #TARGET_PATH: README.md # optional
          #COMMITTER_NAME: GitHubActionBot # optional
          #COMMITTER_EMAIL: action-bot@github.com # optional
          #AUTHOR_NAME: David Frings # optional
          #AUTHOR_EMAIL: test@test.test # optional
          # you can populate email-id with secrets instead
    #steps:
    #  - uses: DavidFrings/waka-readme-stats@master
    #    with:
    #      #https://github.com/anmol098/waka-readme-stats#flags-available
    #      WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    #      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #      LOCALE: "de"
    #      TARGET_PATH: "README.de.md"
    #      SECTION_NAME: "waka"
    #      COMMIT_BY_ME: "False"
    #      COMMIT_MESSAGE: "Updated with Dev Metrics"
    #      COMMIT_USERNAME: "GitHubActionBot"
    #      COMMIT_EMAIL: "action-bot@github.com"
    #      SHOW_UPDATED_DATE: "True"
    #      UPDATED_DATE_FORMAT: "%d/%m/%Y %H:%M:%S"
    #      SHOW_LINES_OF_CODE: "False"
    #      SHOW_TOTAL_CODE_TIME: "False"
    #      SHOW_PROFILE_VIEWS: "False"
    #      SHOW_COMMIT: "False"
    #      SHOW_DAYS_OF_WEEK: "True"
    #      SHOW_LANGUAGE: "True"
    #      SHOW_OS: "False"
    #      SHOW_PROJECTS: "True"
    #      SHOW_TIMEZONE: "False"
    #      SHOW_EDITORS: "True"
    #      SHOW_LANGUAGE_PER_REPO: "True"
    #      SHOW_SHORT_INFO: "True"
    #      SHOW_LOC_CHART: "False"
    #      IGNORED_REPOS: "server, Velocity"
    #      SYMBOL_VERSION: "2"
    #      DEBUG_LOGGING: "True"
